### ISSUE TITLE
CSS Video Brakes

### ISSUE THREAD

**Issue by gastonfariasb** [gastonfariasb/wehaus-web#12]
Samsung Galaxy S3

![image](https://f.cloud.github.com/assets/2659867/347579/561a73ca-9edd-11e2-8bde-8fb279be3290.png)

**Comment by matiasanaya** [comment]
@gastonfariasb es tu codigo

**Comment by matiasanaya** [comment]
@gastonfariasb el video que quedo en git es distinto del que esta en producción. Hace un pull de master, modifica eso y estas listo para hacer el deploy
