### ISSUE TITLE
feedback se rompe en small

### ISSUE THREAD

**Issue by matiasanaya** [gastonfariasb/wehaus-web#4]
Feedback plugin no es responsive, por lo tanto se rompe al achicar el screen. Yo lo sacaria porque es horrible y como esta pagina es solo para caretearla, nadie nos va a dar feedback de verdad por ahi. Siempre nos puede enscribir al mail.

**Comment by gastonfariasb** [comment]
Como quieras, me parecia lindo... creo que esta bueno para caretear. dejalo hasta 2 semanas post GSMWcongress
