### ISSUE TITLE
w1 rompe el diseño en small

### ISSUE THREAD

**Issue by matiasanaya** [gastonfariasb/wehaus-web#8]
Es muy grande la typografia para un mobile device, rompe el diseño.

**Comment by gastonfariasb** [comment]
mmm bi tag? o que cambie por debajo de los x pixels de ancho?
sorry my bad...

**Comment by gastonfariasb** [comment]
A ver, pense que estaria bueno tener una typo especial... pone lo que quieras. yo entre a google y elegi esa entre las primeras 20.
